title: Kendal's Github Page Website
author: KendalUTD
email: kendal.wiggins@utdallas.edu
description: > # this means to ignore newlines until "baseurl:"
 This is an awesome website. This website was created using Github Pages!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
